### ISSUE TITLE
No response from localhost:5050 during publish

### ISSUE THREAD

**Issue by michielpost** [jsakamoto/BlazorWasmPreRendering.Build#1]
This package looks really useful. I tried it with my Blazor wasm app SkyDocs, but it doesn't work. During the publish step, it receives a timeout from the local server.

```
  Start fetching...
  Getting http://127.0.0.1:5050/...
  Using API domain: http://0.1:5050
  Unhandled exception. System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
```

I've created a `private static void ConfigureServices(IServiceCollection services, string baseAddress)` and moved my service configuration there.
Do you know what might be the problem? Is there a way I can help / debug this?

PR in my repo with this prerender package:
https://github.com/michielpost/SkyDocs/pull/15

**Comment by jsakamoto** [comment]
Thank you for reporting!

The reason for this problem is, the "OnInitializedAsync()" method in your app never ends until the login dialog is closed.

The Blazor server-side prerendering waits for completion of the "OnInitializedAsync()" method, but was never ended infinitely (because nobody can fill and submit login form at the server-side prerendering!), so it caused the time out error.

This case's workaround is to open the login dialog in the "OnAfterRendered()" method.

```csharp
// THIS IS "Index.razor.cs" FILE
...
protected override async Task OnInitializedAsync()
{
    ...
    // 👇 MOVE THIS CODE FROM HERE TO ...
    // //No document open, ask user to login
    // if (skyDocsService.CurrentDocument == null)
    // {
    //     if (!skyDocsService.IsLoggedIn)
    //     {
    //          await Login();
    //     }
    // }
}

// 👇 ... TO INSIDE HERE!
protected override async Task OnAfterRenderAsync(bool firstRender)
{
    await base.OnAfterRenderAsync(firstRender);

    if (firstRender)
    {
        //No document open, ask user to login
        if (skyDocsService.CurrentDocument == null)
        {
            if (!skyDocsService.IsLoggedIn)
            {
                await Login();
            }
        }
    }
}
...
```

After I did that in my local machine, the `dotnet publish` was completed as I expected.

![image](https://user-images.githubusercontent.com/95908/121895815-9b878500-cd5b-11eb-8216-82ff02840046.png)

I hope this answer is helpful for you.

**Comment by michielpost** [comment]
Thanks a lot, that fixed the publish step!
