### ISSUE TITLE
BlazorWasmPrerenderingUrlPathToExplicitFetch - alternative suggestion

### ISSUE THREAD

**Issue by drma-dev** [jsakamoto/BlazorWasmPreRendering.Build#27]
I wanted to suggest a tag change or just a new one with different behavior.

currently you have to type all the paths to be recognized. What if you have many paths to type or are they dynamic paths, or that change all the time?

so it would be interesting to read from the sitemap.xml file and process what is there.

**Comment by drma-dev** [comment]
@jsakamoto

**Comment by jsakamoto** [comment]
@drma-dev 

I'm sorry, but I feel like it doesn't make sense. Do you mean that the site in the scenario you mentioned has a lot of pages that are not linked from any pages on that site? Do you desire to save those pages into static files regardless such pages will never indexed by internet search engine crawlers? (Oh, but you said you have a sitemap.xml...)

Anyway, that requirement might be too rare to have a worth to spend my time improving this library, I feel like it so far.

If you don't think so, sorry for bothering you, but please tell me more details about the background and needs of the feature you proposed in this issue.

**Comment by drma-dev** [comment]
what I meant is: when the site has many pages (my example, about 500 pages - which is actually a component that reads different data), it becomes complicated for you to configure all this in the project file. would it make more sense to simply read this from the sitemap file

**Comment by jsakamoto** [comment]
@drma-dev 
> when the site has many pages (my example, about 500 pages - which is actually a component that reads different data),

Does that mean that those pages are not linked to from any page on that site except sitemap.xml?

**Comment by drma-dev** [comment]
[https://www.streamingdiscovery.com/Providers](https://www.streamingdiscovery.com/Providers)

to be more clear. This is the page I'm talking about. There is a link to the page, but it is a dynamically generated link, not static.

each page has a different title, description and content.

**Comment by jsakamoto** [comment]
@drma-dev 
Thank you for letting me know the instance! It is really helpful for me to know precise backgrounds. I'd like to comment on that, but I'm a bit busy right now, so I'll do it later. I appreciate your patience.

**Comment by jsakamoto** [comment]
@drma-dev 

Please let me explain to you the limitations of the static pre-rendering technique before continuing to discuss your proposal in this issue.

First of all, please remember that every request for the same URL path that differs only in query parameters is saved into the same file in the static pre-rendering process.

![image](https://github.com/jsakamoto/BlazorWasmPreRendering.Build/assets/95908/30862ec9-3026-426a-a820-542f5aa4cd69)

Because a static web server can't serve different files for each HTTP request that has the same URL path but only different query parameters.

![image](https://github.com/jsakamoto/BlazorWasmPreRendering.Build/assets/95908/c0147774-ac4a-41bc-ac8f-fdd01a8553b0)

Therefore, if you want to pre-render every page on your Blazor Wasm app into static HTML files, you may have to consider changing the URL routing pattern from using query parameters, like "/Providers?region=MX&language=es-ES", to using URL path fragments, like "/MX/es-ES/Providers".

![image](https://github.com/jsakamoto/BlazorWasmPreRendering.Build/assets/95908/fc0ad749-d2ef-4664-ade6-821f0bfb067c)

I hope the explanation above will be useful for you. And I'll continue to explain the next topic in the following post.

**Comment by jsakamoto** [comment]
@drma-dev 

You don't need to write down each page URL into the `<BlazorWasmPrerenderingUrlPathToExplicitFetch>` MSBuild property as long as those pages are linked from other reachable pages. The "BlazorWasmPreRendering.Build" works like Internet Search Engine Crawlers. That means the "BlazorWasmPreRendering.Build" detects all anchor tag (`<a>`) inside the pre-rendering page and pre-render the URLs that are pointed by the `href` attribute of those anchor tags recursively. It doesn't matter whether those pages are built dynamically on database data or not.

One weak point of this architecture I am aware of by reading the 1st post of this issue is the "BlazorWasmPreRendering.Build" can't detect pages that are navigated by some UI control event, such as selecting drop-down list items, clicking non-anchor buttons. 

![image](https://github.com/jsakamoto/BlazorWasmPreRendering.Build/assets/95908/3b3cc207-764e-4f1f-aa4b-e08a62a2eefd)

I have no good idea now, but I'll keep considering it. Thank you for making me aware.

**Comment by drma-dev** [comment]
@jsakamoto this is my point. you say that the component can recognize each of the links, but that is not what is happening. each of these images is a link, and is not being processed by the component.

**Comment by drma-dev** [comment]
there is my question: the component does not recognize because of the construction of the page is dynamic and not static?

**Comment by jsakamoto** [comment]
@drma-dev 
> the component does not recognize because of the construction of the page is dynamic and not static?

No. As I already mentioned, it doesn't matter whether those pages are built dynamically on database data or not.

However, if those `<a href="...">,,,</a>` elements inside the page are rendered after the `OnInitializedAsync` lifecycle method, the pre-rendering process can not save it into a static HTML file and can not follow those links.

If your Blazor Wasm app exactly renders all `<a href="...">,,,</a>` elements until the end of the `OnInitializedAsync` lifecycle method, those links should be saved into static HTML files as we expected. If not, it might be a bug of the "BlazorWasmPreRendering.Build".

**Comment by drma-dev** [comment]
I understood. in my case they are loaded in OnAfterRenderAsync.

I think it's even a microsoft recommendation, because things like accessing javascript, you can't do it in the initialize method.

Is it a limitation of the component or was it your choice?

**Comment by jsakamoto** [comment]
@drma-dev 

Oh... I noticed that the "Provider" page took some time to load data and render each `<a>` element.

![movie-002](https://github.com/jsakamoto/BlazorWasmPreRendering.Build/assets/95908/0220ef60-60a0-44fa-91e8-9e4140d4635c)

I guess that is the reason why each provider page won't be recognized and won't be pre-rendered.

**Comment by jsakamoto** [comment]
@drma-dev 
> I understood. in my case they are loaded in OnAfterRenderAsync.
> I think it's even a microsoft recommendation, because things like accessing javascript, you can't do it in the initialize method.
> Is it a limitation of the component or was it your choice?

Yes, you can not use JavaScript Interop inside the `OnInitializedAsync` method because during the pre-rendering process, your code runs on a server, not a web browser! So there is NO JavaScript engine in a pre-rendering process! (It is like the usual dotNET console app)

This is a limitation of the "BlazorWasmPreRendering.Build" architecture.

By the way, is it true that you can create a "sitemap.xml" file that covers all required page URLs before running the pre-rendering process, as you told me before?

If the answer is "Yes", I might be able to introduce you to a workaround for this situation.

**Comment by jsakamoto** [comment]
@drma-dev 

If you can prepare a `sitemap.xml` file before running the pre-rendering process, there is a workaround that can make the "BlazorWasmPreRendering.Build" recognize all of those URLs written in that `sitemap.xml`.
 
Could you investigate the sample code I attached below?

[📦BlazorWasmApp1.zip](https://github.com/jsakamoto/BlazorWasmPreRendering.Build/files/12465280/BlazorWasmApp1.zip)

This sample code has a "/sitemap" page, and the sitemap page renders anchor elements for each URLs written inside the `sitemap.xml`. This "/sitemap" page is not linked from any pages because this page is not intended to be shown to any users. Instead, the URL "/sitemap" is specified to the `<BlazorWasmPrerenderingUrlPathToExplicitFetch>` MSBuild property.

The "BlazorWasmPreRendering.Build" will detect the "/sitemap" page and follow all the links that come from the "sitemap.xml" inside the sitemap page.

I hope this workaround will help you for a while.

**Comment by drma-dev** [comment]
ok, at the end of the week I'll try to make these pages recognized with your suggestions and I'll let you know.

**Comment by drma-dev** [comment]
@jsakamoto 

From what I understand, your suggestion is to change the sitemap by code? I wanted to try a more natural solution, before embarking on this workaround. for example, if you run my website here: [(https://www.xml-sitemaps.com/)](https://www.xml-sitemaps.com/) you can't find my links either.

I managed to change the page layout at startup instead of afterrender. but it didn't help anything, I think it's because there's async and await everywhere. so the page will be responsive and appear before I have all the data. If I run everything synchronously, my site will be horribly slow.

**Comment by drma-dev** [comment]
There were so many messages that I even forgot what I wanted.
It doesn't make any sense to expect to read from the sitemap, if the content is dynamic.

When I requested this demand I only had one screen in mind, which was already static. But the way I did it, it wasn't working. Now I managed to find out the reason.

```
Stripping symbols from dotnet.wasm ...
  Compressing Blazor WebAssembly publish artifacts. This may take a while...
  SD.WEB -> /bin/staticsites/61bc3290-e335-4f69-b9fd-9d329460972a-swa-oryx/app/
  Start fetching...[http://127.0.0.1:5050/]
  Getting http://127.0.0.1:5050/...
  Getting http://127.0.0.1:5050/Profile...
  Getting http://127.0.0.1:5050/Providers...
  Getting http://127.0.0.1:5050/Suggestions...
  Getting http://127.0.0.1:5050/Support...
  Getting http://127.0.0.1:5050/login-providers...
  Getting http://127.0.0.1:5050/.auth/login/google...
  Getting http://127.0.0.1:5050/.auth/login/twitter...
  Getting http://127.0.0.1:5050/.auth/login/aad...
  Getting http://127.0.0.1:5050/Terms/en...
  Getting http://127.0.0.1:5050/Privacy/en...
  Getting http://127.0.0.1:5050/Suggestions/Oscar...
  Getting http://127.0.0.1:5050/Suggestions/GoldenGlobes...
  Getting http://127.0.0.1:5050/Suggestions/Bafta...
  Getting http://127.0.0.1:5050/Suggestions/Emmys...
  Getting http://127.0.0.1:5050/Suggestions/FestivalCannes...
  Getting http://127.0.0.1:5050/Suggestions/Berlin...
  Getting http://127.0.0.1:5050/Suggestions/Sundance...
  Getting http://127.0.0.1:5050/Suggestions/Tiff...
  Getting http://127.0.0.1:5050/Suggestions/CriticsChoice...
  Getting http://127.0.0.1:5050/Suggestions/Spirit...
  Getting http://127.0.0.1:5050/Suggestions/Imdb...
  Getting http://127.0.0.1:5050/Suggestions/RottenTomatoes...
  Getting http://127.0.0.1:5050/Suggestions/Metacritic...
  Getting http://127.0.0.1:5050/Suggestions/Tmdb...
  Getting http://127.0.0.1:5050/Suggestions/Trakt...
  Getting http://127.0.0.1:5050/Suggestions/HollywoodReporter...
  Getting http://127.0.0.1:5050/Suggestions/Empire...
  Getting http://127.0.0.1:5050/Suggestions/RollingStone...
  Getting http://127.0.0.1:5050/Suggestions/Filmaffinity...
  Getting http://127.0.0.1:5050/Suggestions/UpcomingMarvel...
  Getting http://127.0.0.1:5050/Suggestions/UpcomingDC...
  Getting http://127.0.0.1:5050/Suggestions/UpcomingStarWars...
  Getting http://127.0.0.1:5050/Suggestions/UpcomingNetflix...
  Getting http://127.0.0.1:5050/Suggestions/UpcomingDisney...
  Getting http://127.0.0.1:5050/Suggestions/GrossingMovies...
  Getting http://127.0.0.1:5050/Suggestions/Movies2023...
  Getting http://127.0.0.1:5050/Suggestions/Movies2024...
  Fetching complete.
```
