### ISSUE TITLE
HeadOutlet doesn't prerender

### ISSUE THREAD

**Issue by NArnott** [jsakamoto/BlazorWasmPreRendering.Build#4]
The new dotnet 6 HeadOutlet doesn't end up in the pre-render.

I want to use this to inject meta/title tags in the Head of the html document for SEO purposes, and while it works in the end-resulting browser page, it doesn't show up in the pre-rendered index.html files.

`builder.RootComponents.Add<HeadOutlet>("head::after");`

https://docs.microsoft.com/en-us/aspnet/core/blazor/components/control-head-content?view=aspnetcore-6.0

**Comment by jsakamoto** [comment]
Yes, I know the new feature `<HeadOutlet>` of .NET6.

But unfortunately, the `<HeadOutlet>` feature will not work well with this package because of this package's mechanism of pre-rendering.

Currently, I'm considering how I can support the `<HeadOutlet>` feature in this package.

By the way, If you are not very particular about the `<HeadOutlet>` feature of .NET6, consider using the `Blazor Head Element Helper` library instead. (follow the next link)

- https://www.nuget.org/packages/Toolbelt.Blazor.HeadElement/

Today, the `Blazor Head Element Helper` will be able to pre-render `<head>` contents to static files with this package in an out-of-the-box experience.

The `Blazor Head Element Helper` was released 3 years ago, and it is kept maintain now, and the number of downloads is over 40,000.

**Comment by NArnott** [comment]
I thought Toolbelt.Blazor.HeadElement uses javascript to update the head elements? If so, does your package prerender with javascript? I don't want a server for prerendering (which is why I liked this package so much).

**Comment by jsakamoto** [comment]
This package doesn't pre-render with javascript, but actually, the combination of the `Toolbelt.Blazor.HeadElement` and this package can pre-render a dynamic `<head>` content to static files because these packages have a special trick!

Please try it 😊

**Comment by NArnott** [comment]
Wow, really worked. Thanks for the suggestion. Would be great to see this work in the native HeadOutlet coming in .Net 6, but for now, this is what I was looking for. Thanks.
